// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB4VQZeN0O4GRfms2GXLQqq1PstIl1E-c',
    appId: '1:987539233312:web:892cd268a914cf86e93a45',
    messagingSenderId: '987539233312',
    projectId: 'ecommerceapp-e17ae',
    authDomain: 'ecommerceapp-e17ae.firebaseapp.com',
    storageBucket: 'ecommerceapp-e17ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA82QkjZqRix_soANXYic7JQDfKjqWbQiQ',
    appId: '1:987539233312:android:1134aa89407f81eee93a45',
    messagingSenderId: '987539233312',
    projectId: 'ecommerceapp-e17ae',
    storageBucket: 'ecommerceapp-e17ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwfFKs8CCMZGsd24HUc-oFFmh5EJGydHA',
    appId: '1:987539233312:ios:6b4d713d7406fbe1e93a45',
    messagingSenderId: '987539233312',
    projectId: 'ecommerceapp-e17ae',
    storageBucket: 'ecommerceapp-e17ae.firebasestorage.app',
    iosClientId: '987539233312-1j460k8gc5seqtk4pe04i9cbccuj0e00.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB4VQZeN0O4GRfms2GXLQqq1PstIl1E-c',
    appId: '1:987539233312:web:e02c0c7cad779ceae93a45',
    messagingSenderId: '987539233312',
    projectId: 'ecommerceapp-e17ae',
    authDomain: 'ecommerceapp-e17ae.firebaseapp.com',
    storageBucket: 'ecommerceapp-e17ae.firebasestorage.app',
  );

}